function J = fSpecDensTwostepMAS(omega,omegaR,tauf,taus,S2)

%Nowacka et al, Langmuir 26, 1688-16856 (2010), Eq. 5

J = 1/3*((1-S2).*(fLorentzSpecDens(omega-omegaR,tauf)+fLorentzSpecDens(omega+omegaR,tauf))+ ...
    S2.*(fLorentzSpecDens(omega-omegaR,taus)+fLorentzSpecDens(omega+omegaR,taus))) + ...
    1/6*((1-S2).*(fLorentzSpecDens(omega-2*omegaR,tauf)+fLorentzSpecDens(omega+2*omegaR,tauf)) + ...
    S2.*(fLorentzSpecDens(omega-2*omegaR,taus)+fLorentzSpecDens(omega+2*omegaR,taus)));
